/* The following code was generated by JFlex 1.4.3 on 15:45 01/11/10 */

package IC.Parser;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 15:45 01/11/10 from the specification file
 * <tt>IC.lex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int SINGLE_LINE_COMMENTS = 2;
  public static final int QUOTE = 6;
  public static final int YYINITIAL = 0;
  public static final int MULTI_LINE_COMMENTS = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\60\1\6\2\0\1\60\22\0\1\60\1\31\1\11\2\0"+
    "\1\25\1\32\1\0\1\12\1\13\1\7\1\24\1\20\1\23\1\26"+
    "\1\10\1\1\11\2\1\0\1\21\1\30\1\22\1\27\2\0\32\4"+
    "\1\16\1\0\1\17\1\0\1\5\1\0\1\37\1\34\1\41\1\47"+
    "\1\36\1\53\1\57\1\56\1\50\1\3\1\40\1\42\1\3\1\46"+
    "\1\51\2\3\1\35\1\43\1\45\1\52\1\54\1\55\1\44\2\3"+
    "\1\14\1\33\1\15\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\2\1\14\3\1\31\1\5\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\16\3\1\45\17\3\1\46\1\3\1\47\6\3\1\50"+
    "\6\3\1\51\1\52\1\53\2\3\1\54\1\3\1\55"+
    "\3\3\1\56\5\3\1\57\1\60\1\3\1\61\2\3"+
    "\1\62\1\63\1\64\1\3\1\65\1\66\1\3\1\67"+
    "\1\70";

  private static int [] zzUnpackAction() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\u0157"+
    "\0\u0188\0\304\0\304\0\u01b9\0\304\0\304\0\304\0\304"+
    "\0\304\0\304\0\304\0\304\0\304\0\u01ea\0\304\0\304"+
    "\0\304\0\304\0\u021b\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310"+
    "\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\u0498"+
    "\0\u04c9\0\u04fa\0\u052b\0\304\0\u055c\0\304\0\304\0\365"+
    "\0\304\0\304\0\304\0\304\0\304\0\304\0\304\0\304"+
    "\0\u058d\0\u05be\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4"+
    "\0\u0715\0\u0746\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u0157\0\u083b"+
    "\0\u086c\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u0992\0\u09c3"+
    "\0\u09f4\0\u0a25\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\u0157\0\u0b1a"+
    "\0\u0b4b\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\u0157"+
    "\0\u0ca2\0\u0cd3\0\u0d04\0\u0d35\0\u0d66\0\u0d97\0\u0157\0\u0157"+
    "\0\u0157\0\u0dc8\0\u0df9\0\u0157\0\u0e2a\0\u0157\0\u0e5b\0\u0e8c"+
    "\0\u0ebd\0\u0157\0\u0eee\0\u0f1f\0\u0f50\0\u0f81\0\u0fb2\0\u0157"+
    "\0\u0157\0\u0fe3\0\u0157\0\u1014\0\u1045\0\u0157\0\u0157\0\u0157"+
    "\0\u1076\0\u0157\0\u0157\0\u10a7\0\u0157\0\u0157";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\11\1\5\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\2\10"+
    "\1\43\1\44\1\45\1\10\1\46\1\47\1\10\1\50"+
    "\2\10\1\51\1\52\1\53\2\10\7\12\1\54\61\12"+
    "\1\55\51\12\11\56\1\57\47\56\62\0\5\60\26\0"+
    "\24\60\2\0\2\7\3\60\26\0\24\60\2\0\5\10"+
    "\26\0\24\10\2\0\5\11\26\0\24\11\10\0\1\61"+
    "\1\62\72\0\1\63\60\0\1\64\60\0\1\65\60\0"+
    "\1\66\70\0\1\67\61\0\1\70\26\0\5\10\26\0"+
    "\1\10\1\71\13\10\1\72\6\10\2\0\5\10\26\0"+
    "\2\10\1\73\21\10\2\0\5\10\26\0\6\10\1\74"+
    "\1\10\1\75\13\10\2\0\5\10\26\0\6\10\1\76"+
    "\6\10\1\77\6\10\2\0\5\10\26\0\2\10\1\100"+
    "\21\10\2\0\5\10\26\0\11\10\1\101\12\10\2\0"+
    "\5\10\26\0\1\10\1\102\20\10\1\103\1\10\2\0"+
    "\5\10\26\0\2\10\1\104\13\10\1\105\5\10\2\0"+
    "\5\10\26\0\12\10\1\106\4\10\1\107\4\10\2\0"+
    "\5\10\26\0\3\10\1\110\20\10\2\0\5\10\26\0"+
    "\15\10\1\111\6\10\2\0\5\10\26\0\22\10\1\112"+
    "\1\10\11\0\1\54\51\0\5\10\26\0\2\10\1\113"+
    "\21\10\2\0\5\10\26\0\15\10\1\114\6\10\2\0"+
    "\5\10\26\0\11\10\1\115\12\10\2\0\5\10\26\0"+
    "\7\10\1\116\14\10\2\0\5\10\26\0\11\10\1\117"+
    "\12\10\2\0\5\10\26\0\3\10\1\120\20\10\2\0"+
    "\5\10\26\0\12\10\1\121\11\10\2\0\5\10\26\0"+
    "\12\10\1\122\11\10\2\0\5\10\26\0\1\10\1\123"+
    "\1\10\1\124\20\10\2\0\5\10\26\0\16\10\1\125"+
    "\5\10\2\0\5\10\26\0\14\10\1\126\7\10\2\0"+
    "\5\10\26\0\21\10\1\127\2\10\2\0\5\10\26\0"+
    "\6\10\1\130\15\10\2\0\5\10\26\0\11\10\1\131"+
    "\12\10\2\0\5\10\26\0\6\10\1\132\15\10\2\0"+
    "\5\10\26\0\14\10\1\133\7\10\2\0\5\10\26\0"+
    "\14\10\1\134\7\10\2\0\5\10\26\0\3\10\1\135"+
    "\20\10\2\0\5\10\26\0\6\10\1\136\15\10\2\0"+
    "\5\10\26\0\16\10\1\137\5\10\2\0\5\10\26\0"+
    "\2\10\1\140\21\10\2\0\5\10\26\0\2\10\1\141"+
    "\21\10\2\0\5\10\26\0\7\10\1\142\14\10\2\0"+
    "\5\10\26\0\11\10\1\143\12\10\2\0\5\10\26\0"+
    "\23\10\1\144\2\0\5\10\26\0\14\10\1\145\7\10"+
    "\2\0\5\10\26\0\11\10\1\146\12\10\2\0\5\10"+
    "\26\0\2\10\1\147\21\10\2\0\5\10\26\0\7\10"+
    "\1\150\14\10\2\0\5\10\26\0\6\10\1\151\15\10"+
    "\2\0\5\10\26\0\2\10\1\152\21\10\2\0\5\10"+
    "\26\0\7\10\1\153\14\10\2\0\5\10\26\0\13\10"+
    "\1\154\10\10\2\0\5\10\26\0\6\10\1\155\15\10"+
    "\2\0\5\10\26\0\4\10\1\156\17\10\2\0\5\10"+
    "\26\0\2\10\1\157\21\10\2\0\5\10\26\0\1\10"+
    "\1\160\22\10\2\0\5\10\26\0\12\10\1\161\11\10"+
    "\2\0\5\10\26\0\7\10\1\162\14\10\2\0\5\10"+
    "\26\0\14\10\1\163\7\10\2\0\5\10\26\0\11\10"+
    "\1\164\12\10\2\0\5\10\26\0\12\10\1\165\11\10"+
    "\2\0\5\10\26\0\14\10\1\166\7\10\2\0\5\10"+
    "\26\0\23\10\1\167\2\0\5\10\26\0\2\10\1\170"+
    "\21\10\2\0\5\10\26\0\2\10\1\171\21\10\2\0"+
    "\5\10\26\0\3\10\1\172\20\10\2\0\5\10\26\0"+
    "\12\10\1\173\11\10\2\0\5\10\26\0\13\10\1\174"+
    "\10\10\2\0\5\10\26\0\12\10\1\175\11\10\2\0"+
    "\5\10\26\0\22\10\1\176\1\10\2\0\5\10\26\0"+
    "\23\10\1\177\2\0\5\10\26\0\5\10\1\200\16\10"+
    "\2\0\5\10\26\0\2\10\1\201\21\10\2\0\5\10"+
    "\26\0\12\10\1\202\11\10\2\0\5\10\26\0\7\10"+
    "\1\203\14\10\2\0\5\10\26\0\16\10\1\204\5\10"+
    "\2\0\5\10\26\0\1\10\1\205\22\10\2\0\5\10"+
    "\26\0\2\10\1\206\21\10\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4312];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\4\1\2\11\1\1\11\11\1\1\4\11"+
    "\21\1\1\11\1\1\2\11\1\1\10\11\116\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  	private StringBuffer curString = new StringBuffer();
  	private int getLine() {return yyline+1;}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 128) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws LexicalError {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new LexicalError(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws LexicalError {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token next_token() throws java.io.IOException, LexicalError {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 13: 
          { return new Token(sym.LB,getLine());
          }
        case 57: break;
        case 31: 
          { return new Token(sym.EQUAL,getLine());
          }
        case 58: break;
        case 42: 
          { return new Token(sym.THIS,getLine());
          }
        case 59: break;
        case 45: 
          { return new Token(sym.BREAK,getLine());
          }
        case 60: break;
        case 26: 
          { curString.append(yytext());
          }
        case 61: break;
        case 47: 
          { return new Token(sym.FALSE,getLine());
          }
        case 62: break;
        case 41: 
          { return new Token(sym.TRUE,getLine());
          }
        case 63: break;
        case 38: 
          { return new Token(sym.NEW,getLine());
          }
        case 64: break;
        case 32: 
          { return new Token(sym.GTE,getLine());
          }
        case 65: break;
        case 16: 
          { return new Token(sym.SEMI,getLine());
          }
        case 66: break;
        case 34: 
          { return new Token(sym.NEQUAL,getLine());
          }
        case 67: break;
        case 10: 
          { return new Token(sym.RP,getLine());
          }
        case 68: break;
        case 21: 
          { return new Token(sym.DOT,getLine());
          }
        case 69: break;
        case 35: 
          { return new Token(sym.LAND,getLine());
          }
        case 70: break;
        case 33: 
          { return new Token(sym.LTE,getLine());
          }
        case 71: break;
        case 12: 
          { return new Token(sym.RCBR,getLine());
          }
        case 72: break;
        case 48: 
          { return new Token(sym.WHILE,getLine());
          }
        case 73: break;
        case 25: 
          { yybegin(YYINITIAL);
          }
        case 74: break;
        case 56: 
          { return new Token(sym.CONTINUE,getLine());
          }
        case 75: break;
        case 14: 
          { return new Token(sym.RB,getLine());
          }
        case 76: break;
        case 46: 
          { return new Token(sym.CLASS,getLine());
          }
        case 77: break;
        case 19: 
          { return new Token(sym.PLUS,getLine());
          }
        case 78: break;
        case 28: 
          { throw new LexicalError(getLine(),"bad input");
          }
        case 79: break;
        case 4: 
          { return new Token(sym.CLASS_ID,getLine(),yytext());
          }
        case 80: break;
        case 2: 
          { return new Token(sym.INTEGER,getLine(),yytext());
          }
        case 81: break;
        case 20: 
          { return new Token(sym.MOD,getLine());
          }
        case 82: break;
        case 11: 
          { return new Token(sym.LCBR,getLine());
          }
        case 83: break;
        case 6: 
          { return new Token(sym.MULTIPLY,getLine());
          }
        case 84: break;
        case 27: 
          { curString.append(yytext());
		yybegin(YYINITIAL);
	 	return new Token(sym.QUOTE, getLine(), curString.toString());
          }
        case 85: break;
        case 1: 
          { throw new LexicalError(getLine(),"Unexpected input: " + yytext());
          }
        case 86: break;
        case 43: 
          { return new Token(sym.NULL,getLine());
          }
        case 87: break;
        case 39: 
          { return new Token(sym.INT,getLine());
          }
        case 88: break;
        case 29: 
          { yybegin(MULTI_LINE_COMMENTS);
          }
        case 89: break;
        case 40: 
          { return new Token(sym.ELSE,getLine());
          }
        case 90: break;
        case 37: 
          { return new Token(sym.IF,getLine());
          }
        case 91: break;
        case 30: 
          { yybegin(SINGLE_LINE_COMMENTS);
          }
        case 92: break;
        case 49: 
          { return new Token(sym.RETURN,getLine());
          }
        case 93: break;
        case 23: 
          { return new Token(sym.LT,getLine());
          }
        case 94: break;
        case 15: 
          { return new Token(sym.COMMA,getLine());
          }
        case 95: break;
        case 55: 
          { return new Token(sym.INTEGER,getLine());
          }
        case 96: break;
        case 36: 
          { return new Token(sym.LOR,getLine());
          }
        case 97: break;
        case 24: 
          { return new Token(sym.LNEG,getLine());
          }
        case 98: break;
        case 7: 
          { return new Token(sym.DIVIDE,getLine());
          }
        case 99: break;
        case 52: 
          { return new Token(sym.STATIC,getLine());
          }
        case 100: break;
        case 44: 
          { return new Token(sym.VOID,getLine());
          }
        case 101: break;
        case 51: 
          { return new Token(sym.STRING,getLine());
          }
        case 102: break;
        case 9: 
          { return new Token(sym.LP,getLine());
          }
        case 103: break;
        case 18: 
          { return new Token(sym.MINUS,getLine());
          }
        case 104: break;
        case 3: 
          { return new Token(sym.ID,getLine(),yytext());
          }
        case 105: break;
        case 53: 
          { return new Token(sym.BOOLEAN,getLine());
          }
        case 106: break;
        case 8: 
          { curString.setLength(0);curString.append(yytext()); yybegin(QUOTE);
          }
        case 107: break;
        case 17: 
          { return new Token(sym.ASSIGN,getLine());
          }
        case 108: break;
        case 50: 
          { return new Token(sym.LENGTH,getLine());
          }
        case 109: break;
        case 22: 
          { return new Token(sym.GT,getLine());
          }
        case 110: break;
        case 54: 
          { return new Token(sym.EXTENDS,getLine());
          }
        case 111: break;
        case 5: 
          { 
          }
        case 112: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case QUOTE: {
              throw new LexicalError(getLine(),"Unexpected EOF");
            }
            case 135: break;
            case MULTI_LINE_COMMENTS: {
              throw new LexicalError(getLine(),"Unexpected EOF");
            }
            case 136: break;
            default:
              {   	return new Token(sym.EOF,getLine());
 }
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
